// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('myApp.about', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/about', {
        templateUrl: 'about/about.html',
        controller: 'AboutCtrl'
      });
    }
  ]).controller('AboutCtrl', ['$scope', '$cookieStore', '$location', function($scope, $cookieStore, $location) {}]);

}).call(this);
