// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('myApp.stage', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/stage', {
        templateUrl: 'stage/stage.html',
        controller: 'StageCtrl'
      });
    }
  ]).controller('StageCtrl', [
    '$scope', '$cookieStore', '$location', function($scope, $cookieStore, $location) {
      var correct, incrementTeam, _ref;
      $scope.go = {
        final: false,
        previous: $cookieStore.get('go').previous
      };
      $scope.go.previous++;
      $cookieStore.put('go', $scope.go);
      incrementTeam = function() {
        var numTeams, previousTeam;
        previousTeam = $cookieStore.get('currentTeam');
        numTeams = parseInt($cookieStore.get('numTeams'));
        if (previousTeam <= numTeams - 1) {
          $scope.currentTeam = previousTeam + 1;
        } else {
          $scope.currentTeam = 1;
        }
        $scope.previousTeam = previousTeam;
        return $cookieStore.put('currentTeam', $scope.currentTeam);
      };
      incrementTeam();
      $scope.correct = correct = (_ref = $cookieStore.get('correct')) != null ? _ref : 0;
      $scope.roundMessages = $cookieStore.get('roundMessages');
      $scope.roundMessage = $cookieStore.get('roundMessage');
      $cookieStore.put('roundMessages', $scope.roundMessages);
      $cookieStore.put('roundMessage', $scope.roundMessage);
      return $scope.scores = $cookieStore.get('scores');
    }
  ]);

}).call(this);
