// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('myApp', ['ngRoute', 'ngCookies', 'myApp.add', 'myApp.about', 'myApp.play', 'myApp.version', 'angulartics', 'angulartics.google.analytics']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.otherwise({
        redirectTo: '/about'
      });
    }
  ]);

}).call(this);
